import os
import io
import logging
from contextlib import asynccontextmanager

from fastapi import FastAPI, UploadFile, File, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import Response, JSONResponse
from PIL import Image
from simple_lama_inpainting import SimpleLama
from ultralytics import FastSAM
import numpy as np
import uvicorn

# ─────────────────────────────────────────────
# Logging
# ─────────────────────────────────────────────
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# ─────────────────────────────────────────────
# Lazy-load the model once on startup (lifespan)
# ─────────────────────────────────────────────
lama_model: SimpleLama | None = None
fastsam_model: FastSAM | None = None

@asynccontextmanager
async def lifespan(app: FastAPI):
    global lama_model, fastsam_model
    logger.info("Loading FastSAM model (may download ~40MB weights on first run)...")
    try:
        fastsam_model = FastSAM("FastSAM-s.pt")
    except Exception as e:
        logger.error(f"Failed to load FastSAM: {e}")
        
    logger.info("Loading LaMa model...")
    lama_model = SimpleLama()
    logger.info("Models loaded and ready!")
    yield
    logger.info("Shutting down.")

# ─────────────────────────────────────────────
# App
# ─────────────────────────────────────────────
app = FastAPI(
    title="Gemini Eraser AI Backend",
    description="Production-grade AI inpainting powered by LaMa.",
    version="1.0.0",
    lifespan=lifespan,
)

# CORS — allow all origins so the Android app can always reach this endpoint
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)

# ─────────────────────────────────────────────
# Routes
# ─────────────────────────────────────────────

@app.get("/", tags=["Health"])
async def root():
    """Quick health check — confirms the server is running."""
    return JSONResponse({"status": "ok", "model": "lama", "ready": lama_model is not None})

@app.get("/health", tags=["Health"])
async def health():
    if lama_model is None or fastsam_model is None:
        raise HTTPException(status_code=503, detail="Models not yet loaded")
    return JSONResponse({"status": "healthy"})

@app.post("/segment", tags=["Segmentation"])
async def segment_image(
    image: UploadFile = File(...),
    normX: float = 0.5,
    normY: float = 0.5
):
    """
    Receives an image and a normalized (0-1) X, Y point.
    Returns a B&W mask generated by FastSAM highlighting the tapped object.
    """
    if fastsam_model is None:
        raise HTTPException(status_code=503, detail="FastSAM not loaded")

    # Validate
    if image.content_type not in ("image/png", "image/jpeg", "image/jpg", "application/octet-stream"):
        raise HTTPException(status_code=415, detail="Unsupported image format")
        
    try:
        img_data = await image.read()
        src = Image.open(io.BytesIO(img_data)).convert("RGB")
        
        px, py = int(normX * src.width), int(normY * src.height)
        logger.info(f"Segmenting point {px}, {py} on {src.size} image...")
        
        # FastSAM magic!
        results = fastsam_model(src, points=[[px, py]], labels=[1], retina_masks=True)
        
        if not results or results[0].masks is None:
             # Return a fully black mask if nothing is detected
             mask_img = Image.new("L", src.size, 0)
        else:
             mask_array = results[0].masks.data[0].cpu().numpy()
             mask_img = Image.fromarray((mask_array * 255).astype(np.uint8), mode="L")
             
             # Double check sizing to match src strictly
             if mask_img.size != src.size:
                 mask_img = mask_img.resize(src.size, Image.NEAREST)

        output = io.BytesIO()
        mask_img.save(output, format="PNG", optimize=True)
        return Response(
            content=output.getvalue(),
            media_type="image/png",
            headers={"X-Model": "fastsam"},
        )
    except Exception as e:
        logger.error(f"Segmentation failed: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"Segmentation error: {str(e)}")

@app.post("/inpaint", tags=["Inpaint"])
async def inpaint(
    image: UploadFile = File(..., description="Original image (PNG/JPG)"),
    mask: UploadFile = File(..., description="B&W mask: white = area to erase"),
):
    """
    Receives a source image and a binary mask.
    Returns the inpainted PNG with the masked region generatively filled.
    """
    if lama_model is None:
        raise HTTPException(status_code=503, detail="Model not yet loaded, please retry in a moment")

    # Validate MIME types
    for upload, name in [(image, "image"), (mask, "mask")]:
        if upload.content_type not in ("image/png", "image/jpeg", "image/jpg", "application/octet-stream"):
            raise HTTPException(status_code=415, detail=f"Unsupported file type for '{name}': {upload.content_type}")

    try:
        img_data  = await image.read()
        mask_data = await mask.read()

        src  = Image.open(io.BytesIO(img_data)).convert("RGB")
        msk  = Image.open(io.BytesIO(mask_data)).convert("L")

        # Ensure mask dimensions match image
        if src.size != msk.size:
            msk = msk.resize(src.size, Image.NEAREST)

        logger.info(f"Processing image {src.size} with mask {msk.size} ...")
        result = lama_model(src, msk)
        logger.info("Inpainting complete.")

        output = io.BytesIO()
        result.save(output, format="PNG", optimize=True)
        return Response(
            content=output.getvalue(),
            media_type="image/png",
            headers={"X-Model": "lama"},
        )
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Inpainting failed: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"Inpainting error: {str(e)}")


if __name__ == "__main__":
    port = int(os.environ.get("PORT", 7860))
    uvicorn.run("main:app", host="0.0.0.0", port=port, log_level="info")
